version: "3"
services:
  maria-server:
    image: mariadb
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    env_file: db/mariadb.env
    networks:
      - backend-network
    healthcheck:
      interval: 30s
      retries: 3
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
      timeout: 30s
  backend-server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      maria-server:
        condition: service_healthy
    ports:
      - 8080:8080
    networks:
      - backend-network
    restart: on-failure

networks:
  backend-network:
    driver: bridge
