spring:
  datasource:
    url: jdbc:mariadb://maria-server:3306/terra
    password: back00112!
    username: back
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        highlight_sql: true
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
        order_inserts: true
        order_updates: true
logging:
  level:
    org.hibernate.sql: info
    org.hibernate.type.descriptor.sql: trace
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    tags-sorter: alpha
    disable-swagger-default-url: true
    path: /swagger
  paths-to-match: /api/**