insert into
    cpu_minute_usage(sampling_date, usage)
values
    (CURRENT_TIMESTAMP, FLOOR(20 + (RAND() * 61))),
    (CURRENT_TIMESTAMP - INTERVAL '1' MINUTE, FLOOR(20 + (RAND() * 61))),
    (CURRENT_TIMESTAMP - INTERVAL '2' MINUTE, FLOOR(20 + (RAND() * 61))),
    (CURRENT_TIMESTAMP - INTERVAL '3' MINUTE, FLOOR(20 + (RAND() * 61))),
    (CURRENT_TIMESTAMP - INTERVAL '4' MINUTE, FLOOR(20 + (RAND() * 61))),
    (CURRENT_TIMESTAMP - INTERVAL '5' MINUTE, FLOOR(20 + (RAND() * 61))),
    (CURRENT_TIMESTAMP - INTERVAL '6' MINUTE, FLOOR(20 + (RAND() * 61))),
    (CURRENT_TIMESTAMP - INTERVAL '7' MINUTE, FLOOR(20 + (RAND() * 61))),
    (CURRENT_TIMESTAMP - INTERVAL '8' MINUTE, FLOOR(20 + (RAND() * 61))),
    (CURRENT_TIMESTAMP - INTERVAL '9' MINUTE, FLOOR(20 + (RAND() * 61))),
    (CURRENT_TIMESTAMP - INTERVAL '10' MINUTE, FLOOR(20 + (RAND() * 61))),
    (CURRENT_TIMESTAMP - INTERVAL '11' MINUTE, FLOOR(20 + (RAND() * 61))),
    (CURRENT_TIMESTAMP - INTERVAL '12' MINUTE, FLOOR(20 + (RAND() * 61))),
    (CURRENT_TIMESTAMP - INTERVAL '13' MINUTE, FLOOR(20 + (RAND() * 61))),
    (CURRENT_TIMESTAMP - INTERVAL '14' MINUTE, FLOOR(20 + (RAND() * 61))),
    (CURRENT_TIMESTAMP - INTERVAL '15' MINUTE, FLOOR(20 + (RAND() * 61))),
    (CURRENT_TIMESTAMP - INTERVAL '16' MINUTE, FLOOR(20 + (RAND() * 61))),
    (CURRENT_TIMESTAMP - INTERVAL '17' MINUTE, FLOOR(20 + (RAND() * 61)));